import Foundation

struct FinancialAnalysisExporter {
    static func buildAnalysisText(
        transactions: [Transaction],
        goals: [Goal],
        selectedMonth: Int,
        selectedYear: Int,
        adults: Int,
        children: Int,
        currencyCode: String,
        calendar: Calendar = .current
    ) -> String {
        let currentStart = startOfMonth(month: selectedMonth, year: selectedYear, calendar: calendar)
        let previousStart = calendar.date(byAdding: .month, value: -1, to: currentStart) ?? currentStart
        let nextStart = calendar.date(byAdding: .month, value: 1, to: currentStart) ?? currentStart

        let current = monthSnapshot(
            title: "CURRENT MONTH",
            start: currentStart,
            transactions: transactions,
            currencyCode: currencyCode,
            calendar: calendar
        )
        let previous = monthSnapshot(
            title: "PREVIOUS MONTH",
            start: previousStart,
            transactions: transactions,
            currencyCode: currencyCode,
            calendar: calendar
        )
        let next = nextMonthSnapshot(
            start: nextStart,
            transactions: transactions,
            currencyCode: currencyCode,
            calendar: calendar
        )

        let instruction = "You are a financial assistant helping analyze personal expense data. The data below comes from FinAInce, the app the user uses to manage their finances. Analyze the data, identify patterns, risks, and opportunities to improve financial health. Be practical, concise, and action-oriented."

        var lines: [String] = [
            instruction,
            "",
            "=== FINAINCE DATA START ===",
            "",
            "These are financial data generated by the FinAInce app, used by the user to manage their personal expenses.",
            "",
            "USER PROFILE:",
            "- Adults: \(adults)",
            "- Children: \(children)",
            "",
            "GOALS:"
        ]

        let goalLines = goalsSection(
            goals: goals,
            transactions: transactions,
            monthStart: currentStart,
            currencyCode: currencyCode,
            calendar: calendar
        )
        lines.append(contentsOf: goalLines.isEmpty ? ["- No goals configured"] : goalLines)

        lines.append(contentsOf: [
            "",
            "CURRENT MONTH:",
            "Total spent: \(current.totalSpent.asCurrency(currencyCode))",
            "Top categories:"
        ])
        lines.append(contentsOf: current.topCategories.isEmpty ? ["- No spending in this period"] : current.topCategories)
        lines.append("Top transactions:")
        lines.append(contentsOf: current.topTransactions.isEmpty ? ["- No transactions in this period"] : current.topTransactions)

        lines.append(contentsOf: [
            "",
            "PREVIOUS MONTH:",
            "Total spent: \(previous.totalSpent.asCurrency(currencyCode))",
            "Key differences:"
        ])
        lines.append(contentsOf: keyDifferences(current: current, previous: previous, currencyCode: currencyCode))
        lines.append("Top categories:")
        lines.append(contentsOf: previous.topCategories.isEmpty ? ["- No spending in this period"] : previous.topCategories)
        lines.append("Top transactions:")
        lines.append(contentsOf: previous.topTransactions.isEmpty ? ["- No transactions in this period"] : previous.topTransactions)

        lines.append(contentsOf: [
            "",
            "NEXT MONTH:",
            "Planned expenses: \(next.plannedExpenses.asCurrency(currencyCode))",
            "Pending commitments:"
        ])
        lines.append(contentsOf: next.pendingCommitments.isEmpty ? ["- No pending commitments found"] : next.pendingCommitments)

        lines.append(contentsOf: [
            "",
            "=== FINAINCE DATA END ==="
        ])

        return lines.joined(separator: "\n")
    }

    private struct MonthSnapshot {
        let totalSpent: Double
        let categoryTotals: [String: Double]
        let topCategories: [String]
        let topTransactions: [String]
    }

    private struct NextMonthSnapshot {
        let plannedExpenses: Double
        let pendingCommitments: [String]
    }

    private static func startOfMonth(month: Int, year: Int, calendar: Calendar) -> Date {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = 1
        return calendar.date(from: components) ?? calendar.startOfDay(for: Date())
    }

    private static func endOfMonth(start: Date, calendar: Calendar) -> Date {
        calendar.date(byAdding: .month, value: 1, to: start) ?? start
    }

    private static func transactions(inMonthStarting start: Date, from transactions: [Transaction], calendar: Calendar) -> [Transaction] {
        let end = endOfMonth(start: start, calendar: calendar)
        return transactions.filter { $0.date >= start && $0.date < end }
    }

    private static func monthSnapshot(
        title: String,
        start: Date,
        transactions: [Transaction],
        currencyCode: String,
        calendar: Calendar
    ) -> MonthSnapshot {
        let monthTransactions = transactions(inMonthStarting: start, from: transactions, calendar: calendar)
            .filter { $0.type == .expense }
        let totalSpent = monthTransactions.reduce(0) { $0 + $1.amount }
        let categoryTotals = categoryTotals(for: monthTransactions)

        let topCategories = categoryTotals
            .sorted { $0.value > $1.value }
            .prefix(5)
            .map { "- \($0.key): \($0.value.asCurrency(currencyCode))" }

        let topTransactions = monthTransactions
            .sorted { $0.amount > $1.amount }
            .prefix(5)
            .map { "- \(transactionDescription($0)): \($0.amount.asCurrency(currencyCode))" }

        return MonthSnapshot(
            totalSpent: totalSpent,
            categoryTotals: categoryTotals,
            topCategories: Array(topCategories),
            topTransactions: Array(topTransactions)
        )
    }

    private static func nextMonthSnapshot(
        start: Date,
        transactions: [Transaction],
        currencyCode: String,
        calendar: Calendar
    ) -> NextMonthSnapshot {
        let monthTransactions = transactions(inMonthStarting: start, from: transactions, calendar: calendar)
            .filter { transaction in
                transaction.type == .expense && (
                    !transaction.isPaid ||
                    transaction.recurrenceType == .monthly ||
                    transaction.recurrenceType == .installment
                )
            }
            .sorted { first, second in
                if first.date == second.date { return first.amount > second.amount }
                return first.date < second.date
            }

        let plannedExpenses = monthTransactions.reduce(0) { $0 + $1.amount }
        let pendingCommitments = monthTransactions.prefix(10).map { transaction in
            let date = shortDateFormatter.string(from: transaction.date)
            let status = transaction.isPaid ? "scheduled" : "pending"
            let recurrence = recurrenceLabel(for: transaction)
            return "- \(date) · \(transactionDescription(transaction)): \(transaction.amount.asCurrency(currencyCode)) · \(status)\(recurrence)"
        }

        return NextMonthSnapshot(
            plannedExpenses: plannedExpenses,
            pendingCommitments: Array(pendingCommitments)
        )
    }

    private static func goalsSection(
        goals: [Goal],
        transactions: [Transaction],
        monthStart: Date,
        currencyCode: String,
        calendar: Calendar
    ) -> [String] {
        let monthTransactions = transactions(inMonthStarting: monthStart, from: transactions, calendar: calendar)
            .filter { $0.type == .expense }

        return goals
            .filter { $0.isActive }
            .sorted { $0.createdAt < $1.createdAt }
            .map { goal in
                let spent = spentAmount(for: goal, in: monthTransactions)
                let progress = goal.targetAmount > 0 ? min(999, (spent / goal.targetAmount) * 100) : 0
                let categoryName = goal.category?.name ?? goal.title
                return "- Category: \(categoryName): \(goal.targetAmount.asCurrency(currencyCode)) target — \(Int(progress.rounded()))% completed"
            }
    }

    private static func spentAmount(for goal: Goal, in transactions: [Transaction]) -> Double {
        guard let goalCategory = goal.category else {
            return transactions.reduce(0) { $0 + $1.amount }
        }

        return transactions
            .filter { transaction in
                let root = transaction.category?.parent ?? transaction.category
                return root?.persistentModelID == goalCategory.persistentModelID ||
                    transaction.category?.persistentModelID == goalCategory.persistentModelID
            }
            .reduce(0) { $0 + $1.amount }
    }

    private static func keyDifferences(
        current: MonthSnapshot,
        previous: MonthSnapshot,
        currencyCode: String
    ) -> [String] {
        guard current.totalSpent > 0 || previous.totalSpent > 0 else {
            return ["- No spending in either period"]
        }

        let diff = current.totalSpent - previous.totalSpent
        let direction = diff >= 0 ? "higher" : "lower"
        var lines = ["- Current month is \(abs(diff).asCurrency(currencyCode)) \(direction) than previous month"]

        let categories = Set(current.categoryTotals.keys).union(previous.categoryTotals.keys)
        let categoryDiffs = categories.map { category -> (String, Double) in
            let currentValue = current.categoryTotals[category] ?? 0
            let previousValue = previous.categoryTotals[category] ?? 0
            return (category, currentValue - previousValue)
        }
        .sorted { abs($0.1) > abs($1.1) }
        .prefix(3)

        for item in categoryDiffs where abs(item.1) >= 0.01 {
            let direction = item.1 >= 0 ? "up" : "down"
            lines.append("- \(item.0): \(direction) \(abs(item.1).asCurrency(currencyCode))")
        }

        return lines
    }

    private static func categoryTotals(for transactions: [Transaction]) -> [String: Double] {
        var totals: [String: Double] = [:]
        for transaction in transactions {
            let categoryName = (transaction.category?.parent ?? transaction.category)?.name ?? "Uncategorized"
            totals[categoryName, default: 0] += transaction.amount
        }
        return totals
    }

    private static func transactionDescription(_ transaction: Transaction) -> String {
        transaction.placeName ?? transaction.subcategory?.name ?? transaction.category?.name ?? "Transaction"
    }

    private static func recurrenceLabel(for transaction: Transaction) -> String {
        switch transaction.recurrenceType {
        case .none:
            return ""
        case .monthly:
            return " · monthly recurring"
        case .installment:
            if let index = transaction.installmentIndex, let total = transaction.installmentTotal {
                return " · installment \(index)/\(total)"
            }
            return " · installment"
        }
    }

    private static let shortDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return formatter
    }()
}
