import Foundation

// MARK: - SF Symbols — Comprehensive grouped list (SF Symbols 5 / iOS 17)
// Mirrors Apple's official category structure in the SF Symbols app.

struct SFSymbolGroup: Identifiable {
    let id    = UUID()
    let title: String
    let symbols: [String]
}

// swiftlint:disable line_length
let allSFSymbolGroups: [SFSymbolGroup] = [

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Comunicação", symbols: [
        "message", "message.fill", "message.circle", "message.circle.fill",
        "message.badge", "message.badge.fill", "message.badge.circle", "message.badge.circle.fill",
        "bubble.left", "bubble.left.fill", "bubble.right", "bubble.right.fill",
        "bubble.left.and.bubble.right", "bubble.left.and.bubble.right.fill",
        "exclamationmark.bubble", "exclamationmark.bubble.fill",
        "quote.bubble", "quote.bubble.fill",
        "text.bubble", "text.bubble.fill",
        "captions.bubble", "captions.bubble.fill",
        "info.bubble", "info.bubble.fill",
        "questionmark.bubble", "questionmark.bubble.fill",
        "phone", "phone.fill", "phone.circle", "phone.circle.fill",
        "phone.arrow.up.right", "phone.arrow.down.left",
        "phone.badge.plus", "phone.badge.checkmark",
        "phone.connection", "phone.and.waveform", "phone.and.waveform.fill",
        "video", "video.fill", "video.circle", "video.circle.fill",
        "video.slash", "video.slash.fill", "video.badge.plus", "video.badge.checkmark",
        "envelope", "envelope.fill", "envelope.circle", "envelope.circle.fill",
        "envelope.open", "envelope.open.fill",
        "envelope.badge", "envelope.badge.fill",
        "envelope.arrow.triangle.branch", "envelope.arrow.triangle.branch.fill",
        "paperplane", "paperplane.fill", "paperplane.circle", "paperplane.circle.fill",
        "mic", "mic.fill", "mic.circle", "mic.circle.fill",
        "mic.slash", "mic.slash.fill", "mic.badge.plus", "mic.badge.xmark",
        "megaphone", "megaphone.fill",
        "speaker", "speaker.fill", "speaker.slash", "speaker.slash.fill",
        "speaker.wave.1", "speaker.wave.1.fill", "speaker.wave.2", "speaker.wave.2.fill",
        "speaker.wave.3", "speaker.wave.3.fill",
        "antenna.radiowaves.left.and.right", "antenna.radiowaves.left.and.right.circle",
        "dot.radiowaves.left.and.right", "dot.radiowaves.right",
        "network", "network.slash", "network.badge.shield.half.filled",
        "bell", "bell.fill", "bell.circle", "bell.circle.fill",
        "bell.slash", "bell.slash.fill", "bell.badge", "bell.badge.fill",
        "bell.badge.waveform", "bell.badge.waveform.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Clima", symbols: [
        "sun.max", "sun.max.fill", "sun.min", "sun.min.fill",
        "sun.horizon", "sun.horizon.fill", "sun.and.horizon", "sun.and.horizon.fill",
        "sunrise", "sunrise.fill", "sunset", "sunset.fill",
        "moon", "moon.fill", "moon.circle", "moon.circle.fill",
        "moon.stars", "moon.stars.fill", "moon.haze", "moon.haze.fill",
        "zzz", "sparkle", "sparkles",
        "cloud", "cloud.fill", "cloud.sun", "cloud.sun.fill",
        "cloud.moon", "cloud.moon.fill", "cloud.rain", "cloud.rain.fill",
        "cloud.drizzle", "cloud.drizzle.fill", "cloud.heavyrain", "cloud.heavyrain.fill",
        "cloud.snow", "cloud.snow.fill", "cloud.sleet", "cloud.sleet.fill",
        "cloud.hail", "cloud.hail.fill", "cloud.fog", "cloud.fog.fill",
        "cloud.tornado", "cloud.tornado.fill", "cloud.bolt", "cloud.bolt.fill",
        "cloud.bolt.rain", "cloud.bolt.rain.fill",
        "wind", "wind.snow", "tornado", "hurricane",
        "tropicalstorm", "thermometer.sun", "thermometer.sun.fill",
        "thermometer.snowflake", "thermometer.medium", "thermometer.medium.slash",
        "thermometer.high", "thermometer.low",
        "snowflake", "drop", "drop.fill", "drop.circle", "drop.circle.fill",
        "humidity", "humidity.fill", "umbrella", "umbrella.fill",
        "cloud.moon.rain", "cloud.moon.rain.fill",
        "aqi.low", "aqi.medium", "aqi.high",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Mapas & Localização", symbols: [
        "map", "map.fill", "mappin", "mappin.and.ellipse", "mappin.slash",
        "mappin.circle", "mappin.circle.fill", "mappin.square", "mappin.square.fill",
        "location", "location.fill", "location.circle", "location.circle.fill",
        "location.slash", "location.slash.fill", "location.north", "location.north.fill",
        "location.north.line", "location.north.line.fill",
        "globe", "globe.americas", "globe.americas.fill",
        "globe.europe.africa", "globe.europe.africa.fill",
        "globe.asia.australia", "globe.asia.australia.fill",
        "globe.central.south.asia", "globe.central.south.asia.fill",
        "compass.drawing", "map.circle", "map.circle.fill",
        "mountain.2", "mountain.2.fill", "building.2", "building.2.fill",
        "building", "building.fill", "building.columns", "building.columns.fill",
        "building.2.crop.circle", "building.2.crop.circle.fill",
        "flag", "flag.fill", "flag.circle", "flag.circle.fill",
        "flag.slash", "flag.badge.ellipsis", "flag.badge.ellipsis.fill",
        "signpost.left", "signpost.left.fill", "signpost.right", "signpost.right.fill",
        "road.lanes", "road.lanes.curved.left", "road.lanes.curved.right",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Objetos & Ferramentas", symbols: [
        "wrench.and.screwdriver", "wrench.and.screwdriver.fill",
        "wrench", "wrench.fill", "hammer", "hammer.fill",
        "screwdriver", "screwdriver.fill",
        "paintbrush", "paintbrush.fill", "paintbrush.pointed", "paintbrush.pointed.fill",
        "ruler", "ruler.fill",
        "level", "level.fill", "pencil", "pencil.circle", "pencil.circle.fill",
        "pencil.tip", "pencil.tip.crop.circle",
        "scissors", "scissors.circle", "scissors.circle.fill",
        "trash", "trash.fill", "trash.circle", "trash.circle.fill",
        "trash.slash", "trash.slash.fill",
        "folder", "folder.fill", "folder.circle", "folder.circle.fill",
        "folder.badge.plus", "folder.badge.minus",
        "tray", "tray.fill", "tray.circle", "tray.circle.fill",
        "tray.and.arrow.up", "tray.and.arrow.up.fill",
        "tray.and.arrow.down", "tray.and.arrow.down.fill",
        "archivebox", "archivebox.fill", "archivebox.circle", "archivebox.circle.fill",
        "doc", "doc.fill", "doc.circle", "doc.circle.fill",
        "doc.text", "doc.text.fill",
        "doc.richtext", "doc.richtext.fill",
        "clipboard", "clipboard.fill",
        "note", "note.text", "note.text.badge.plus",
        "bookmark", "bookmark.fill", "bookmark.circle", "bookmark.circle.fill",
        "bookmark.slash", "bookmark.slash.fill",
        "tag", "tag.fill", "tag.circle", "tag.circle.fill",
        "tag.slash", "tag.slash.fill",
        "briefcase", "briefcase.fill", "briefcase.circle", "briefcase.circle.fill",
        "case", "case.fill",
        "latch.2.case", "latch.2.case.fill",
        "cross.case", "cross.case.fill",
        "backpack", "backpack.fill", "backpack.circle", "backpack.circle.fill",
        "lock", "lock.fill", "lock.circle", "lock.circle.fill",
        "lock.slash", "lock.slash.fill", "lock.open", "lock.open.fill",
        "key", "key.fill", "key.horizontal", "key.horizontal.fill",
        "key.icloud", "key.icloud.fill",
        "lanyardcard", "lanyardcard.fill",
        "magnifyingglass", "magnifyingglass.circle", "magnifyingglass.circle.fill",
        "flashlight.off.fill", "flashlight.on.fill",
        "lightbulb", "lightbulb.fill", "lightbulb.circle", "lightbulb.circle.fill",
        "lightbulb.slash", "lightbulb.slash.fill",
        "bolt", "bolt.fill", "bolt.circle", "bolt.circle.fill",
        "bolt.slash", "bolt.slash.fill", "bolt.badge.xmark",
        "flame", "flame.fill", "flame.circle", "flame.circle.fill",
        "drop.degreesign", "thermometer", "gauge",
        "stethoscope", "syringe", "syringe.fill",
        "printer", "printer.fill", "scanner", "scanner.fill",
        "shredder", "shredder.fill",
        "gift", "gift.fill", "gift.circle", "gift.circle.fill",
        "balloon", "balloon.fill", "party.popper", "party.popper.fill",
        "calendar", "calendar.circle", "calendar.circle.fill",
        "calendar.badge.plus", "calendar.badge.minus", "calendar.badge.clock",
        "calendar.day.timeline.left", "calendar.day.timeline.right",
        "clock", "clock.fill", "clock.circle", "clock.circle.fill",
        "clock.arrow.circlepath", "alarm", "alarm.fill",
        "stopwatch", "stopwatch.fill", "timer", "timer.circle", "timer.circle.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Dispositivos", symbols: [
        "iphone", "iphone.gen1", "iphone.gen2", "iphone.gen3",
        "iphone.slash", "iphone.badge.play",
        "ipad", "ipad.gen1", "ipad.gen2",
        "ipad.landscape", "ipad.gen1.landscape",
        "mac.pro.gen1", "mac.pro.gen3",
        "macbook", "macbook.gen1", "macbook.gen2",
        "desktopcomputer", "macmini", "macmini.fill",
        "macpro.gen1", "macpro.gen1.fill",
        "applewatch", "applewatch.case.inset.filled", "applewatch.slash",
        "airpods", "airpodspro", "airpods.gen3", "airpodspro.right",
        "headphones", "headphones.circle", "headphones.circle.fill",
        "earpods",
        "appletv", "appletv.fill",
        "homepod", "homepod.fill", "homepod.mini", "homepod.mini.fill",
        "homepod.and.homepod.mini", "homepod.and.homepod.mini.fill",
        "hifispeaker", "hifispeaker.fill", "hifispeaker.2", "hifispeaker.2.fill",
        "tv", "tv.fill", "tv.circle", "tv.circle.fill", "tv.slash", "tv.slash.fill",
        "display", "display.trianglebadge.exclamationmark",
        "keyboard", "keyboard.fill", "keyboard.badge.ellipsis", "keyboard.slash",
        "computermouse", "computermouse.fill", "trackpad", "trackpad.fill",
        "gamecontroller", "gamecontroller.fill",
        "printer", "printer.fill", "printer.dotmatrix", "printer.dotmatrix.fill",
        "scanner", "scanner.fill",
        "camera", "camera.fill", "camera.circle", "camera.circle.fill",
        "camera.shutter.button", "camera.shutter.button.fill",
        "camera.aperture",
        "photo", "photo.fill", "photo.circle", "photo.circle.fill",
        "photo.artframe", "photo.stack", "photo.stack.fill",
        "video.fill.badge.plus", "video.fill.badge.checkmark",
        "battery.100", "battery.75", "battery.50", "battery.25",
        "battery.0", "battery.100.bolt", "battery.slash",
        "minus.plus.batteryblock", "minus.plus.batteryblock.fill",
        "bolt.fill.batteryblock", "bolt.fill.batteryblock.fill",
        "cpu", "cpu.fill", "memorychip", "memorychip.fill",
        "server.rack", "externaldrive", "externaldrive.fill",
        "internaldrive", "internaldrive.fill", "opticaldiscdrive", "opticaldiscdrive.fill",
        "sdcard", "sdcard.fill",
        "simcard", "simcard.fill", "esim", "esim.fill",
        "cable.connector", "cable.connector.horizontal",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Conectividade", symbols: [
        "wifi", "wifi.circle", "wifi.circle.fill",
        "wifi.slash", "wifi.exclamationmark",
        "wifi.router", "wifi.router.fill",
        "antenna.radiowaves.left.and.right", "antenna.radiowaves.left.and.right.circle",
        "antenna.radiowaves.left.and.right.circle.fill",
        "bluetooth", "dot.radiowaves.left.and.right", "dot.radiowaves.right",
        "cellularbars", "4g", "5g", "lte",
        "network", "network.slash", "network.badge.shield.half.filled",
        "shareplay", "airplayaudio", "airplayaudio.circle", "airplayaudio.circle.fill",
        "airplayvideo", "airplayvideo.circle", "airplayvideo.circle.fill",
        "airpodspro.chargingcase.wireless", "airpodspro.chargingcase.wireless.fill",
        "arrow.triangle.2.circlepath",
        "link", "link.circle", "link.circle.fill", "link.badge.plus",
        "personalhotspot", "personalhotspot.circle", "personalhotspot.circle.fill",
        "bonjour", "icloud", "icloud.fill", "icloud.circle", "icloud.circle.fill",
        "icloud.slash", "icloud.slash.fill",
        "icloud.and.arrow.up", "icloud.and.arrow.up.fill",
        "icloud.and.arrow.down", "icloud.and.arrow.down.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Transporte", symbols: [
        "car", "car.fill", "car.circle", "car.circle.fill",
        "car.2", "car.2.fill",
        "car.rear", "car.rear.fill", "car.side", "car.side.fill",
        "car.top.lane.dashed.departure.left", "car.top.lane.dashed.arrival.right",
        "suv.side", "suv.side.fill", "pickup.truck.side", "pickup.truck.side.fill",
        "bus", "bus.fill", "bus.doubledecker", "bus.doubledecker.fill",
        "tram", "tram.fill", "tram.circle", "tram.circle.fill",
        "tram.tunnel.fill",
        "ferry", "ferry.fill",
        "airplane", "airplane.circle", "airplane.circle.fill",
        "airplane.arrival", "airplane.departure",
        "bicycle", "bicycle.circle", "bicycle.circle.fill",
        "scooter",
        "fuelpump", "fuelpump.fill", "fuelpump.circle", "fuelpump.circle.fill",
        "fuelpump.slash", "fuelpump.slash.fill",
        "evplug.us.ccs1", "evplug.us.ccs1.fill", "evplug.us.type1", "evplug.us.type1.fill",
        "parkingsign", "parkingsign.circle", "parkingsign.circle.fill",
        "parkingsign.brace",
        "road.lanes", "road.lanes.curved.left", "road.lanes.curved.right",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.run", "figure.run.circle", "figure.run.circle.fill",
        "figure.hiking", "figure.outdoor.cycle", "figure.indoor.cycle",
        "figure.snowboarding", "figure.skiing.downhill",
        "sailboat", "sailboat.fill",
        "cablecar", "lightrail",
        "sprinkler", "sprinkler.fill", "sprinkler.and.droplets", "sprinkler.and.droplets.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Pessoas & Gestos", symbols: [
        "person", "person.fill", "person.circle", "person.circle.fill",
        "person.badge.plus", "person.badge.minus", "person.badge.clock",
        "person.badge.key", "person.badge.key.fill",
        "person.2", "person.2.fill", "person.2.circle", "person.2.circle.fill",
        "person.3", "person.3.fill", "person.3.sequence", "person.3.sequence.fill",
        "person.crop.circle", "person.crop.circle.fill",
        "person.crop.circle.badge.plus", "person.crop.circle.badge.minus",
        "person.crop.circle.badge.checkmark", "person.crop.circle.badge.xmark",
        "person.crop.square", "person.crop.square.fill",
        "person.bust", "person.bust.fill",
        "figure", "figure.2", "figure.2.and.child.holdinghands",
        "figure.child", "figure.child.circle", "figure.child.circle.fill",
        "figure.stand", "figure.stand.dress",
        "face.smiling", "face.smiling.fill",
        "face.dashed", "face.dashed.fill",
        "hands.clap", "hands.clap.fill",
        "hand.raised", "hand.raised.fill", "hand.raised.circle", "hand.raised.circle.fill",
        "hand.raised.slash", "hand.raised.slash.fill",
        "hand.thumbsup", "hand.thumbsup.fill", "hand.thumbsup.circle", "hand.thumbsup.circle.fill",
        "hand.thumbsdown", "hand.thumbsdown.fill",
        "hand.point.up", "hand.point.up.fill", "hand.point.up.left", "hand.point.up.left.fill",
        "hand.point.right", "hand.point.right.fill",
        "hand.point.left", "hand.point.left.fill",
        "hand.draw", "hand.draw.fill",
        "hand.tap", "hand.tap.fill",
        "hands.and.sparkles", "hands.and.sparkles.fill",
        "eye", "eye.fill", "eye.circle", "eye.circle.fill",
        "eye.slash", "eye.slash.fill",
        "eyes", "eyes.inverse",
        "ear", "ear.fill", "ear.badge.checkmark",
        "nose", "nose.fill",
        "mouth", "mouth.fill",
        "brain", "brain.fill", "brain.head.profile", "brain.head.profile.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Casa & Moradia", symbols: [
        "house", "house.fill", "house.circle", "house.circle.fill",
        "house.badge.plus", "house.badge.plus.fill",
        "house.and.flag", "house.and.flag.fill",
        "homekit",
        "bed.double", "bed.double.fill", "bed.double.circle", "bed.double.circle.fill",
        "sofa", "sofa.fill", "chair.lounge", "chair.lounge.fill",
        "bathtub", "bathtub.fill", "shower", "shower.fill",
        "shower.handheld", "shower.handheld.fill",
        "toilet", "toilet.fill", "sink", "sink.fill",
        "washer", "washer.fill", "dryer", "dryer.fill",
        "dishwasher", "dishwasher.fill",
        "oven", "oven.fill", "microwave", "microwave.fill",
        "refrigerator", "refrigerator.fill",
        "stove", "stove.fill",
        "air.conditioner.horizontal", "air.conditioner.horizontal.fill",
        "air.conditioner.vertical", "air.conditioner.vertical.fill",
        "air.purifier", "air.purifier.fill",
        "humidifier", "humidifier.fill",
        "dehumidifier", "dehumidifier.fill",
        "fan.floor", "fan.floor.fill", "fan.ceiling", "fan.ceiling.fill",
        "fan.desk", "fan.desk.fill",
        "lightswitch.on", "lightswitch.off",
        "poweroutlet.type.b", "poweroutlet.type.b.fill",
        "door.left.hand.closed", "door.left.hand.open",
        "door.garage.closed", "door.garage.open",
        "window.casement.closed", "window.casement.open",
        "blinds.vertical.closed", "blinds.vertical.open",
        "blinds.horizontal.closed", "blinds.horizontal.open",
        "curtains.closed", "curtains.open",
        "pipe.and.drop", "pipe.and.drop.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Saúde & Fitness", symbols: [
        "heart", "heart.fill", "heart.circle", "heart.circle.fill",
        "heart.slash", "heart.slash.fill",
        "heart.text.square", "heart.text.square.fill",
        "cross", "cross.fill", "cross.circle", "cross.circle.fill",
        "staroflife", "staroflife.fill", "staroflife.circle", "staroflife.circle.fill",
        "pills", "pills.fill", "pills.circle", "pills.circle.fill",
        "pill", "pill.fill", "pill.circle", "pill.circle.fill",
        "cross.vial", "cross.vial.fill",
        "bandage", "bandage.fill",
        "stethoscope", "stethoscope.circle", "stethoscope.circle.fill",
        "syringe", "syringe.fill",
        "facemask", "facemask.fill",
        "thermometer", "thermometer.sun", "thermometer.snowflake",
        "tooth", "tooth.fill",
        "eye.and.hand.point.left.and.right",
        "lungs", "lungs.fill",
        "brain", "brain.fill", "brain.head.profile",
        "kidneys", "kidneys.fill", "liver", "liver.fill",
        "figure.run", "figure.run.circle", "figure.run.circle.fill",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.hiking", "figure.outdoor.cycle", "figure.indoor.cycle",
        "figure.swimming", "figure.pool.swim",
        "figure.strengthtraining.traditional", "figure.strengthtraining.functional",
        "figure.yoga", "figure.pilates", "figure.mind.and.body",
        "figure.dance", "figure.martial.arts",
        "figure.climbing", "figure.skiing.downhill", "figure.snowboarding",
        "figure.golf", "figure.tennis", "figure.basketball",
        "figure.soccer", "figure.football",
        "figure.baseball", "figure.volleyball",
        "dumbbell", "dumbbell.fill",
        "sportscourt", "sportscourt.fill", "sportscourt.circle", "sportscourt.circle.fill",
        "sleep", "sleep.circle", "sleep.circle.fill",
        "waveform.path.ecg", "waveform.path.ecg.rectangle", "waveform.path.ecg.rectangle.fill",
        "heart.rate", "pulse",
        "medical.thermometer", "medical.thermometer.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Natureza", symbols: [
        "leaf", "leaf.fill", "leaf.circle", "leaf.circle.fill",
        "leaf.arrow.circlepath",
        "tree", "tree.fill", "tree.circle", "tree.circle.fill",
        "teddybear", "teddybear.fill",
        "pawprint", "pawprint.fill", "pawprint.circle", "pawprint.circle.fill",
        "hare", "hare.fill",
        "tortoise", "tortoise.fill",
        "lizard", "lizard.fill",
        "bird", "bird.fill", "bird.circle", "bird.circle.fill",
        "fish", "fish.fill", "fish.circle", "fish.circle.fill",
        "ant", "ant.fill", "ant.circle", "ant.circle.fill",
        "ladybug", "ladybug.fill",
        "fossil.shell", "fossil.shell.fill",
        "carrot", "carrot.fill",
        "flame", "flame.fill", "flame.circle", "flame.circle.fill",
        "water.waves", "water.waves.and.arrow.up", "water.waves.and.arrow.down",
        "mountain.2", "mountain.2.fill",
        "globe.europe.africa", "globe.europe.africa.fill",
        "moon.stars", "moon.stars.fill",
        "sun.max", "sun.max.fill",
        "cloud", "cloud.fill",
        "wind",
        "snowflake",
        "drop", "drop.fill",
        "humidity", "humidity.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Alimentação & Bebida", symbols: [
        "fork.knife", "fork.knife.circle", "fork.knife.circle.fill",
        "cart", "cart.fill", "cart.circle", "cart.circle.fill",
        "cart.badge.plus", "cart.badge.minus",
        "basket", "basket.fill",
        "bag", "bag.fill", "bag.circle", "bag.circle.fill",
        "bag.badge.plus", "bag.badge.minus",
        "cup.and.saucer", "cup.and.saucer.fill",
        "mug", "mug.fill",
        "wineglass", "wineglass.fill",
        "birthday.cake", "birthday.cake.fill",
        "takeoutbag.and.cup.and.straw", "takeoutbag.and.cup.and.straw.fill",
        "popcorn", "popcorn.fill",
        "carrot", "carrot.fill",
        "fish", "fish.fill",
        "frying.pan", "frying.pan.fill",
        "oven.fill",
        "microwave.fill",
        "refrigerator.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Educação", symbols: [
        "book", "book.fill", "book.circle", "book.circle.fill",
        "book.closed", "book.closed.fill", "book.closed.circle", "book.closed.circle.fill",
        "books.vertical", "books.vertical.fill", "books.vertical.circle", "books.vertical.circle.fill",
        "text.book.closed", "text.book.closed.fill",
        "graduationcap", "graduationcap.fill", "graduationcap.circle", "graduationcap.circle.fill",
        "studentdesk",
        "pencil", "pencil.circle", "pencil.circle.fill", "pencil.tip",
        "pencil.and.outline",
        "pen", "highlighter",
        "ruler", "ruler.fill",
        "backpack", "backpack.fill", "backpack.circle", "backpack.circle.fill",
        "newspaper", "newspaper.fill", "newspaper.circle", "newspaper.circle.fill",
        "doc.text", "doc.text.fill",
        "doc.richtext", "doc.richtext.fill",
        "list.bullet", "list.bullet.circle", "list.bullet.circle.fill",
        "checkmark.rectangle", "checkmark.rectangle.fill",
        "questionmark.circle", "questionmark.circle.fill",
        "lightbulb", "lightbulb.fill",
        "globe", "globe.americas", "globe.europe.africa",
        "magnifyingglass",
        "scope",
        "atom",
        "function",
        "sum",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Lazer & Entretenimento", symbols: [
        "gamecontroller", "gamecontroller.fill",
        "arcade.stick", "arcade.stick.and.arrow.left.and.arrow.right",
        "playstation.logo", "xbox.logo",
        "joystick", "joystick.fill",
        "die.face.1", "die.face.2", "die.face.3", "die.face.4", "die.face.5", "die.face.6",
        "dice", "dice.fill",
        "puzzlepiece", "puzzlepiece.fill", "puzzlepiece.extension", "puzzlepiece.extension.fill",
        "music.note", "music.note.list",
        "music.mic", "music.mic.circle", "music.mic.circle.fill",
        "music.quarternote.3",
        "waveform", "waveform.circle", "waveform.circle.fill",
        "film", "film.fill", "film.circle", "film.circle.fill",
        "ticket", "ticket.fill",
        "theatermasks", "theatermasks.fill",
        "tv", "tv.fill",
        "airplayvideo",
        "photo", "photo.fill",
        "camera", "camera.fill",
        "paintbrush", "paintbrush.fill",
        "paintpalette", "paintpalette.fill",
        "sportscourt", "sportscourt.fill",
        "beach.umbrella", "beach.umbrella.fill",
        "balloon", "balloon.fill",
        "party.popper", "party.popper.fill",
        "fireworks",
        "sportscar.fill",
        "bicycle",
        "figure.dance", "figure.yoga",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Compras & Moda", symbols: [
        "bag", "bag.fill", "bag.circle", "bag.circle.fill",
        "cart", "cart.fill",
        "basket", "basket.fill",
        "tshirt", "tshirt.fill",
        "handbag", "handbag.fill",
        "shoe", "shoe.fill", "shoe.2", "shoe.2.fill",
        "watch.analog",
        "crown", "crown.fill",
        "sparkles",
        "tag", "tag.fill",
        "gift", "gift.fill",
        "giftcard", "giftcard.fill",
        "purchased", "purchased.circle", "purchased.circle.fill",
        "star", "star.fill",
        "heart", "heart.fill",
        "wand.and.sparkles", "wand.and.sparkles.inverse",
        "storefront", "storefront.fill",
        "building.storefront", "building.storefront.fill",
        "figure.dress.line.vertical.figure",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Finanças", symbols: [
        "banknote", "banknote.fill",
        "creditcard", "creditcard.fill", "creditcard.circle", "creditcard.circle.fill",
        "creditcard.and.123", "creditcard.trianglebadge.exclamationmark",
        "dollarsign", "dollarsign.circle", "dollarsign.circle.fill",
        "dollarsign.square", "dollarsign.square.fill",
        "brazilianrealsign", "brazilianrealsign.circle", "brazilianrealsign.circle.fill",
        "eurosign", "eurosign.circle", "eurosign.circle.fill",
        "sterlingsign", "sterlingsign.circle", "sterlingsign.circle.fill",
        "yensign", "yensign.circle", "yensign.circle.fill",
        "bitcoinsign", "bitcoinsign.circle", "bitcoinsign.circle.fill",
        "percent",
        "chart.bar", "chart.bar.fill", "chart.bar.doc.horizontal", "chart.bar.doc.horizontal.fill",
        "chart.pie", "chart.pie.fill",
        "chart.line.uptrend.xyaxis", "chart.line.downtrend.xyaxis",
        "chart.line.flattrend.xyaxis", "chart.xyaxis.line",
        "arrow.up.right", "arrow.down.right",
        "building.columns", "building.columns.fill",
        "safe", "safe.fill",
        "lock.rectangle", "lock.rectangle.fill",
        "qrcode", "qrcode.viewfinder",
        "barcode", "barcode.viewfinder",
        "wallet.pass", "wallet.pass.fill",
        "arrow.left.arrow.right", "arrow.left.arrow.right.circle", "arrow.left.arrow.right.circle.fill",
        "repeat", "repeat.circle", "repeat.circle.fill",
        "clock", "clock.fill",
        "calendar",
        "list.bullet.rectangle", "list.bullet.rectangle.fill",
        "doc.text.magnifyingglass",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Mídia & Controles", symbols: [
        "play", "play.fill", "play.circle", "play.circle.fill",
        "play.rectangle", "play.rectangle.fill",
        "pause", "pause.fill", "pause.circle", "pause.circle.fill",
        "pause.rectangle", "pause.rectangle.fill",
        "stop", "stop.fill", "stop.circle", "stop.circle.fill",
        "record.circle", "record.circle.fill",
        "playpause", "playpause.fill",
        "forward", "forward.fill", "forward.circle", "forward.circle.fill",
        "backward", "backward.fill", "backward.circle", "backward.circle.fill",
        "forward.end", "forward.end.fill", "forward.end.alt", "forward.end.alt.fill",
        "backward.end", "backward.end.fill", "backward.end.alt", "backward.end.alt.fill",
        "forward.frame", "forward.frame.fill", "backward.frame", "backward.frame.fill",
        "shuffle", "shuffle.circle", "shuffle.circle.fill",
        "repeat", "repeat.1", "repeat.circle", "repeat.circle.fill",
        "infinity", "infinity.circle", "infinity.circle.fill",
        "music.note", "music.note.list", "music.mic",
        "waveform", "waveform.circle", "waveform.circle.fill",
        "equalizer",
        "speaker", "speaker.fill", "speaker.slash", "speaker.slash.fill",
        "speaker.wave.1", "speaker.wave.2", "speaker.wave.3",
        "headphones",
        "airplayaudio", "airplayvideo",
        "pip", "pip.fill", "pip.enter", "pip.exit",
        "rectangle.on.rectangle", "rectangle.on.rectangle.fill",
        "tv.and.hifispeaker.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Edição & Texto", symbols: [
        "pencil", "pencil.circle", "pencil.circle.fill",
        "pencil.tip", "pencil.tip.crop.circle",
        "pencil.and.outline",
        "square.and.pencil", "square.and.pencil.circle", "square.and.pencil.circle.fill",
        "rectangle.and.pencil.and.ellipsis",
        "scribble", "scribble.variable",
        "highlighter",
        "signature",
        "scissors", "scissors.circle", "scissors.circle.fill",
        "scissors.badge.ellipsis",
        "doc.on.doc", "doc.on.doc.fill",
        "doc.on.clipboard", "doc.on.clipboard.fill",
        "clipboard", "clipboard.fill",
        "list.bullet", "list.number", "list.dash", "list.triangle",
        "list.star", "list.bullet.indent", "list.bullet.below.rectangle",
        "text.alignleft", "text.aligncenter", "text.alignright", "text.justify",
        "bold", "italic", "underline", "strikethrough",
        "textformat", "textformat.abc", "textformat.size", "textformat.subscript", "textformat.superscript",
        "character", "character.cursor.ibeam",
        "text.badge.plus", "text.badge.minus", "text.badge.checkmark", "text.badge.xmark",
        "text.badge.star",
        "arrow.uturn.left", "arrow.uturn.right",
        "arrow.uturn.backward", "arrow.uturn.forward",
        "checkmark.circle", "checkmark.circle.fill",
        "xmark.circle", "xmark.circle.fill",
        "plus.circle", "plus.circle.fill",
        "minus.circle", "minus.circle.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Setas", symbols: [
        "arrow.right", "arrow.left", "arrow.up", "arrow.down",
        "arrow.right.circle", "arrow.right.circle.fill",
        "arrow.left.circle", "arrow.left.circle.fill",
        "arrow.up.circle", "arrow.up.circle.fill",
        "arrow.down.circle", "arrow.down.circle.fill",
        "arrow.right.square", "arrow.right.square.fill",
        "arrow.up.right", "arrow.down.right", "arrow.up.left", "arrow.down.left",
        "arrow.up.right.circle", "arrow.up.right.circle.fill",
        "arrow.up.left.circle", "arrow.up.left.circle.fill",
        "arrow.down.right.circle", "arrow.down.right.circle.fill",
        "arrow.down.left.circle", "arrow.down.left.circle.fill",
        "arrow.up.and.down", "arrow.left.and.right",
        "arrow.up.and.down.circle", "arrow.up.and.down.circle.fill",
        "arrow.left.and.right.circle", "arrow.left.and.right.circle.fill",
        "arrow.turn.up.right", "arrow.turn.up.left",
        "arrow.turn.down.right", "arrow.turn.down.left",
        "arrow.turn.right.up", "arrow.turn.right.down",
        "arrow.turn.left.up", "arrow.turn.left.down",
        "arrow.uturn.up", "arrow.uturn.down", "arrow.uturn.left", "arrow.uturn.right",
        "arrow.uturn.up.circle", "arrow.uturn.down.circle",
        "arrow.clockwise", "arrow.counterclockwise",
        "arrow.clockwise.circle", "arrow.clockwise.circle.fill",
        "arrow.counterclockwise.circle", "arrow.counterclockwise.circle.fill",
        "arrow.2.squarepath",
        "arrow.triangle.2.circlepath", "arrow.triangle.2.circlepath.circle",
        "arrow.triangle.2.circlepath.circle.fill",
        "chevron.right", "chevron.left", "chevron.up", "chevron.down",
        "chevron.right.circle", "chevron.right.circle.fill",
        "chevron.left.circle", "chevron.left.circle.fill",
        "chevron.up.circle", "chevron.up.circle.fill",
        "chevron.down.circle", "chevron.down.circle.fill",
        "chevron.right.2", "chevron.left.2", "chevron.up.2", "chevron.down.2",
        "chevron.compact.right", "chevron.compact.left", "chevron.compact.up", "chevron.compact.down",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Formas", symbols: [
        "circle", "circle.fill", "circle.dotted", "circle.dashed",
        "circle.inset.filled", "circle.lefthalf.filled", "circle.righthalf.filled",
        "circle.bottomhalf.filled", "circle.tophalf.filled",
        "oval", "oval.fill",
        "capsule", "capsule.fill",
        "square", "square.fill", "square.dotted", "square.dashed",
        "rectangle", "rectangle.fill", "rectangle.dotted", "rectangle.dashed",
        "triangle", "triangle.fill",
        "diamond", "diamond.fill",
        "octagon", "octagon.fill",
        "hexagon", "hexagon.fill",
        "pentagon", "pentagon.fill",
        "seal", "seal.fill",
        "star", "star.fill", "star.circle", "star.circle.fill",
        "star.slash", "star.slash.fill",
        "star.leadinghalf.filled",
        "sparkle", "sparkles",
        "plus.circle", "plus.circle.fill", "plus.square", "plus.square.fill",
        "minus.circle", "minus.circle.fill",
        "multiply.circle", "multiply.circle.fill",
        "divide.circle", "divide.circle.fill",
        "equal.circle", "equal.circle.fill",
        "checkmark.circle", "checkmark.circle.fill",
        "checkmark.square", "checkmark.square.fill",
        "xmark.circle", "xmark.circle.fill",
        "xmark.square", "xmark.square.fill",
        "questionmark.circle", "questionmark.circle.fill",
        "questionmark.square", "questionmark.square.fill",
        "exclamationmark.circle", "exclamationmark.circle.fill",
        "exclamationmark.square", "exclamationmark.square.fill",
        "info.circle", "info.circle.fill",
        "info.square", "info.square.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Privacidade & Segurança", symbols: [
        "lock", "lock.fill", "lock.circle", "lock.circle.fill",
        "lock.slash", "lock.slash.fill", "lock.open", "lock.open.fill",
        "lock.open.rotation",
        "lock.rectangle", "lock.rectangle.fill",
        "lock.rectangle.on.rectangle", "lock.rectangle.on.rectangle.fill",
        "lock.icloud", "lock.icloud.fill",
        "key", "key.fill", "key.horizontal", "key.horizontal.fill",
        "key.viewfinder",
        "key.icloud", "key.icloud.fill",
        "shield", "shield.fill", "shield.slash", "shield.slash.fill",
        "shield.lefthalf.filled", "shield.checkered",
        "checkmark.shield", "checkmark.shield.fill",
        "xmark.shield", "xmark.shield.fill",
        "exclamationmark.shield", "exclamationmark.shield.fill",
        "eye", "eye.fill", "eye.slash", "eye.slash.fill",
        "hand.raised", "hand.raised.fill",
        "person.badge.shield.checkmark", "person.badge.shield.checkmark.fill",
        "network.badge.shield.half.filled",
        "touchid", "faceid",
        "icloud.and.arrow.up", "icloud.and.arrow.down",
        "arrow.up.doc.on.clipboard",
        "doc.badge.gearshape", "doc.badge.gearshape.fill",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Acessibilidade", symbols: [
        "accessibility", "accessibility.fill",
        "accessibility.badge.arrow.up.right",
        "figure.walk.motion", "figure.walk.motion.trianglebadge.exclamationmark",
        "figure.seated.side.air.upper", "figure.seated.side.air.distribution.lower",
        "figure.roll", "figure.roll.runningpace",
        "figure.outdoor.cycle",
        "ear.and.waveform", "ear.trianglebadge.exclamationmark",
        "hand.point.up.braille", "hand.raised.fingers.spread", "hand.raised.fingers.spread.fill",
        "eye.trianglebadge.exclamationmark",
        "brain.head.profile",
        "waveform.path.ecg.rectangle", "waveform.path.ecg.rectangle.fill",
        "phone.and.waveform", "phone.and.waveform.fill",
        "character.textbox",
        "captions.bubble", "captions.bubble.fill",
        "text.and.command.macwindow",
        "sun.max", "textformat.size",
        "lightspectrum.horizontal",
        "cursorarrow.motionlines",
    ]),

    // ─────────────────────────────────────────────────────────────────────
    .init(title: "Geral & Outros", symbols: [
        "ellipsis", "ellipsis.circle", "ellipsis.circle.fill",
        "ellipsis.rectangle", "ellipsis.rectangle.fill",
        "ellipsis.vertical.bubble", "ellipsis.vertical.bubble.fill",
        "gear", "gear.circle", "gear.circle.fill",
        "gearshape", "gearshape.fill", "gearshape.circle", "gearshape.circle.fill",
        "gearshape.2", "gearshape.2.fill",
        "slider.horizontal.3", "slider.horizontal.below.rectangle",
        "slider.vertical.3",
        "switch.2", "toggle.power.off", "power",
        "exclamationmark.triangle", "exclamationmark.triangle.fill",
        "exclamationmark.octagon", "exclamationmark.octagon.fill",
        "checkmark", "xmark", "plus", "minus",
        "multiply", "divide", "equal", "lessthan", "greaterthan",
        "number", "number.circle", "number.circle.fill",
        "square.grid.2x2", "square.grid.3x3", "square.grid.4x3.fill",
        "rectangle.grid.1x2", "rectangle.grid.2x2", "rectangle.grid.3x1",
        "mosaic", "mosaic.fill",
        "sidebar.left", "sidebar.right", "sidebar.leading", "sidebar.trailing",
        "square.split.2x1", "square.split.1x2", "square.split.2x2",
        "square.split.bottomrightquarter",
        "square.and.arrow.up", "square.and.arrow.up.fill",
        "square.and.arrow.down", "square.and.arrow.down.fill",
        "square.and.arrow.up.on.square", "square.and.arrow.up.on.square.fill",
        "rectangle.portrait.and.arrow.right", "rectangle.portrait.and.arrow.right.fill",
        "arrow.up.forward.square", "arrow.up.forward.square.fill",
        "qrcode", "qrcode.viewfinder",
        "barcode", "barcode.viewfinder",
        "cube", "cube.fill", "cube.transparent", "cube.transparent.fill",
        "shippingbox", "shippingbox.fill", "shippingbox.circle", "shippingbox.circle.fill",
        "suitcase", "suitcase.fill", "suitcase.cart", "suitcase.cart.fill",
        "ticket", "ticket.fill",
    ]),
]
// swiftlint:enable line_length
