import Foundation

// MARK: - Busca em Português para SF Symbols
//
// Dicionário: palavra/expressão em PT-BR → lista de fragmentos do nome do SF Symbol.
// A busca é feita normalizando acentos e caixa, e usando "contains" em ambos os lados.

/// Retorna os símbolos de `allSFSymbolGroups` que correspondem a `query`
/// considerando tanto o nome inglês do símbolo quanto os termos em português.
func sfSymbolsMatching(_ query: String) -> [String] {
    let all = allSFSymbolGroups.flatMap(\.symbols)
    guard !query.isEmpty else { return all }

    let q = query
        .lowercased()
        .folding(options: .diacriticInsensitive, locale: Locale(identifier: "pt_BR"))

    // 1. Match direto no nome inglês do símbolo
    let byEnglish = all.filter {
        $0.folding(options: .diacriticInsensitive, locale: .current)
            .lowercased()
            .contains(q)
    }

    // 2. Match via mapeamento português → inglês
    var englishFragments: Set<String> = []
    for (ptTerm, enFragments) in sfSymbolPortugueseMap {
        let normalized = ptTerm
            .folding(options: .diacriticInsensitive, locale: Locale(identifier: "pt_BR"))
        if normalized.contains(q) || q.contains(normalized) {
            enFragments.forEach { englishFragments.insert($0) }
        }
    }

    let byPortuguese: [String]
    if englishFragments.isEmpty {
        byPortuguese = []
    } else {
        byPortuguese = all.filter { sym in
            englishFragments.contains { sym.contains($0) }
        }
    }

    // 3. União preservando ordem (inglês primeiro)
    var seen = Set<String>()
    return (byEnglish + byPortuguese).filter { seen.insert($0).inserted }
}

// MARK: - Dicionário PT-BR → fragmentos SF Symbol

/// Chave: palavra ou expressão em PT-BR (a comparação normaliza acentos).
/// Valor: array de fragmentos que aparecem nos nomes dos SF Symbols.
// swiftlint:disable file_length
let sfSymbolPortugueseMap: [String: [String]] = [

    // ── Clima & Natureza ─────────────────────────────────────────────────
    "sol":                  ["sun"],
    "solar":                ["sun"],
    "lua":                  ["moon"],
    "estrela":              ["star"],
    "estrelas":             ["star"],
    "nuvem":                ["cloud", "icloud"],
    "chuva":                ["rain", "drizzle"],
    "neve":                 ["snow", "snowflake"],
    "granizo":              ["hail"],
    "neblina":              ["fog"],
    "nevoa":                ["fog"],
    "raio":                 ["bolt", "thunder"],
    "trovao":               ["thunder", "bolt"],
    "tempestade":           ["storm", "tornado", "hurricane"],
    "tornado":              ["tornado"],
    "furacao":              ["hurricane"],
    "vento":                ["wind"],
    "gota":                 ["drop"],
    "agua":                 ["drop", "water", "waves"],
    "fogo":                 ["flame", "fire"],
    "chama":                ["flame"],
    "floco":                ["snowflake"],
    "termometro":           ["thermometer"],
    "temperatura":          ["thermometer"],
    "umidade":              ["humidity"],
    "guarda-chuva":         ["umbrella"],
    "amanhecer":            ["sunrise"],
    "anoitecer":            ["sunset"],
    "nascer do sol":        ["sunrise"],
    "por do sol":           ["sunset"],
    "horizonte":            ["horizon"],
    "folha":                ["leaf"],
    "arvore":               ["tree"],
    "planta":               ["leaf", "tree"],
    "natureza":             ["leaf", "tree", "mountain"],
    "montanha":             ["mountain"],
    "onda":                 ["wave", "waves"],
    "mar":                  ["water", "waves"],
    "praia":                ["beach", "umbrella", "beach.umbrella"],
    "arco-iris":            ["rainbow"],

    // ── Animais ──────────────────────────────────────────────────────────
    "pata":                 ["pawprint"],
    "animal":               ["pawprint", "hare", "bird", "fish"],
    "coelho":               ["hare"],
    "tartaruga":            ["tortoise"],
    "lagarto":              ["lizard"],
    "passaro":              ["bird"],
    "peixe":                ["fish"],
    "formiga":              ["ant"],
    "joaninha":             ["ladybug"],
    "bicho":                ["pawprint", "ant"],
    "inseto":               ["ant", "ladybug"],
    "pet":                  ["pawprint"],
    "gato":                 ["pawprint"],
    "cachorro":             ["pawprint"],

    // ── Pessoas & Gestos ─────────────────────────────────────────────────
    "pessoa":               ["person"],
    "pessoas":              ["person"],
    "usuario":              ["person"],
    "perfil":               ["person"],
    "grupo":                ["person.2", "person.3"],
    "familia":              ["person.2", "person.3", "figure.2"],
    "crianca":              ["figure.child"],
    "homem":                ["figure", "person"],
    "mulher":               ["figure.stand.dress", "person"],
    "mao":                  ["hand"],
    "gesto":                ["hand"],
    "aplauso":              ["hands.clap"],
    "joinha":               ["thumbsup"],
    "polegar":              ["thumbsup", "thumbsdown"],
    "apontar":              ["hand.point"],
    "olho":                 ["eye"],
    "olhos":                ["eyes"],
    "ouvido":               ["ear"],
    "nariz":                ["nose"],
    "boca":                 ["mouth"],
    "cerebro":              ["brain"],
    "rosto":                ["face"],
    "sorriso":              ["face.smiling"],
    "emoji":                ["face.smiling"],

    // ── Comunicação ──────────────────────────────────────────────────────
    "mensagem":             ["message", "bubble"],
    "chat":                 ["bubble", "message"],
    "conversa":             ["bubble", "message"],
    "balao":                ["bubble", "balloon"],
    "telefone":             ["phone"],
    "ligacao":              ["phone"],
    "chamada":              ["phone"],
    "videochamada":         ["video"],
    "email":                ["envelope"],
    "carta":                ["envelope"],
    "correio":              ["envelope", "mailbox"],
    "enviar":               ["paperplane"],
    "microfone":            ["mic", "music.mic"],
    "microfones":           ["mic"],
    "caixa de som":         ["speaker"],
    "alto falante":         ["speaker", "megaphone"],
    "megafone":             ["megaphone"],
    "antena":               ["antenna"],
    "sinal":                ["antenna", "wifi", "cellularbars"],
    "sino":                 ["bell"],
    "notificacao":          ["bell"],
    "alerta":               ["bell", "exclamationmark"],

    // ── Casa & Moradia ────────────────────────────────────────────────────
    "casa":                 ["house", "home"],
    "lar":                  ["house", "home"],
    "apartamento":          ["building"],
    "predio":               ["building"],
    "cama":                 ["bed"],
    "sofa":                 ["sofa"],
    "poltrona":             ["chair"],
    "banheira":             ["bathtub"],
    "chuveiro":             ["shower"],
    "vaso":                 ["toilet"],
    "pia":                  ["sink"],
    "lavadora":             ["washer"],
    "maquina de lavar":     ["washer"],
    "secadora":             ["dryer"],
    "lava-loucas":          ["dishwasher"],
    "forno":                ["oven"],
    "microondas":           ["microwave"],
    "geladeira":            ["refrigerator"],
    "fogao":                ["stove"],
    "ar condicionado":      ["air.conditioner"],
    "arcondicionado":       ["air.conditioner"],
    "ventilador":           ["fan"],
    "purificador":          ["air.purifier"],
    "umidificador":         ["humidifier"],
    "lampada":              ["lightbulb"],
    "luz":                  ["lightbulb"],
    "interruptor":          ["lightswitch"],
    "tomada":               ["poweroutlet"],
    "porta":                ["door"],
    "janela":               ["window"],
    "cortina":              ["curtains", "blinds"],
    "persianas":            ["blinds"],
    "cadeado":              ["lock"],
    "chave":                ["key"],
    "cano":                 ["pipe"],

    // ── Transporte ───────────────────────────────────────────────────────
    "carro":                ["car"],
    "automovel":            ["car"],
    "veiculo":              ["car", "bus", "tram"],
    "onibus":               ["bus"],
    "metro":                ["tram"],
    "trem":                 ["tram", "lightrail"],
    "aviao":                ["airplane"],
    "voo":                  ["airplane"],
    "bicicleta":            ["bicycle"],
    "bike":                 ["bicycle"],
    "patinete":             ["scooter"],
    "barco":                ["ferry", "sailboat"],
    "navio":                ["ferry"],
    "veleiro":              ["sailboat"],
    "combustivel":          ["fuelpump"],
    "gasolina":             ["fuelpump"],
    "estacionamento":       ["parkingsign"],
    "pedestre":             ["figure.walk"],
    "caminhada":            ["figure.walk", "figure.hiking"],
    "corrida":              ["figure.run"],
    "estrada":              ["road.lanes"],
    "bondinho":             ["cablecar"],
    "taxi":                 ["car"],
    "uber":                 ["car"],

    // ── Saúde & Fitness ───────────────────────────────────────────────────
    "coracao":              ["heart"],
    "saude":                ["heart", "cross", "stethoscope"],
    "medicina":             ["cross", "pills", "stethoscope"],
    "remedio":              ["pills", "pill"],
    "comprimido":           ["pill", "pills"],
    "seringa":              ["syringe"],
    "vacina":               ["syringe"],
    "estetoscopio":         ["stethoscope"],
    "curativo":             ["bandage"],
    "dente":                ["tooth"],
    "pulmao":               ["lungs"],
    "academia":             ["dumbbell", "figure.strengthtraining"],
    "haltere":              ["dumbbell"],
    "musculacao":           ["dumbbell", "figure.strengthtraining"],
    "ioga":                 ["figure.yoga"],
    "yoga":                 ["figure.yoga"],
    "natacao":              ["figure.swimming"],
    "ciclismo":             ["figure.outdoor.cycle", "figure.indoor.cycle"],
    "futebol":              ["figure.soccer", "sportscourt"],
    "basquete":             ["figure.basketball", "sportscourt"],
    "golfe":                ["figure.golf"],
    "esqui":                ["figure.skiing"],
    "snowboard":            ["figure.snowboarding"],
    "escalada":             ["figure.climbing"],
    "artes marciais":       ["figure.martial.arts"],
    "pilates":              ["figure.pilates"],
    "danca":                ["figure.dance"],
    "sono":                 ["sleep", "moon"],
    "frequencia cardiaca":  ["heart.rate", "waveform.path.ecg"],
    "pulso":                ["pulse", "waveform"],
    "termometro medico":    ["medical.thermometer"],
    "mascara":              ["facemask"],

    // ── Alimentação & Bebida ──────────────────────────────────────────────
    "comida":               ["fork.knife", "cart", "takeoutbag"],
    "refeicao":             ["fork.knife"],
    "garfo":                ["fork.knife"],
    "faca":                 ["fork.knife"],
    "restaurante":          ["fork.knife"],
    "cafe":                 ["cup.and.saucer", "mug"],
    "cha":                  ["cup.and.saucer", "mug"],
    "caneca":               ["mug"],
    "vinho":                ["wineglass"],
    "bebida":               ["wineglass", "cup", "mug"],
    "bolo":                 ["birthday.cake"],
    "aniversario":          ["birthday.cake", "party.popper", "balloon"],
    "delivery":             ["takeoutbag"],
    "lanche":               ["takeoutbag", "popcorn"],
    "pipoca":               ["popcorn"],
    "cenoura":              ["carrot"],
    "mercado":              ["cart", "basket"],
    "supermercado":         ["cart", "basket"],
    "compras":              ["cart", "bag", "basket"],
    "sacola":               ["bag", "basket"],
    "carrinho":             ["cart"],
    "cesta":                ["basket"],

    // ── Finanças ──────────────────────────────────────────────────────────
    "dinheiro":             ["banknote", "dollarsign", "creditcard"],
    "cedula":               ["banknote"],
    "cartao":               ["creditcard"],
    "cartao de credito":    ["creditcard"],
    "cartao de debito":     ["creditcard"],
    "real":                 ["brazilianrealsign"],
    "reais":                ["brazilianrealsign"],
    "dolar":                ["dollarsign"],
    "euro":                 ["eurosign"],
    "libra":                ["sterlingsign"],
    "iene":                 ["yensign"],
    "bitcoin":              ["bitcoinsign"],
    "porcentagem":          ["percent"],
    "desconto":             ["percent", "tag"],
    "grafico":              ["chart"],
    "investimento":         ["chart.line.uptrend"],
    "banco":                ["building.columns"],
    "cofre":                ["safe"],
    "carteira":             ["wallet"],
    "transferencia":        ["arrow.left.arrow.right"],
    "pix":                  ["arrow.left.arrow.right", "qrcode"],
    "pagamento":            ["creditcard", "banknote"],
    "recibo":               ["doc.text", "list.bullet.rectangle"],
    "fatura":               ["doc.text", "list.bullet.rectangle"],
    "extrato":              ["list.bullet.rectangle"],
    "saldo":                ["banknote", "creditcard"],
    "despesa":              ["arrow.down", "creditcard"],
    "receita":              ["arrow.up", "banknote"],
    "lucro":                ["chart.line.uptrend", "arrow.up"],
    "prejuizo":             ["chart.line.downtrend", "arrow.down"],
    "meta":                 ["flag", "star"],
    "orcamento":            ["chart.bar", "list.bullet"],

    // ── Educação ──────────────────────────────────────────────────────────
    "livro":                ["book"],
    "livros":               ["books"],
    "leitura":              ["book"],
    "estudo":               ["book", "graduationcap"],
    "escola":               ["graduationcap", "backpack"],
    "faculdade":            ["graduationcap"],
    "universidade":         ["graduationcap", "building.columns"],
    "diploma":              ["graduationcap"],
    "mochila":              ["backpack"],
    "lapis":                ["pencil"],
    "caneta":               ["pen", "pencil"],
    "regua":                ["ruler"],
    "jornal":               ["newspaper"],
    "documento":            ["doc", "doc.text"],
    "arquivo":              ["doc", "folder"],
    "pasta":                ["folder", "briefcase"],
    "anotacao":             ["note.text"],
    "lista":                ["list.bullet"],
    "checklist":            ["checklist", "checkmark.circle"],
    "globo":                ["globe"],
    "mundo":                ["globe"],
    "lupa":                 ["magnifyingglass"],
    "pesquisa":             ["magnifyingglass"],
    "atomo":                ["atom"],
    "ciencia":              ["atom", "stethoscope"],
    "matematica":           ["function", "sum", "divide"],

    // ── Lazer & Entretenimento ────────────────────────────────────────────
    "jogo":                 ["gamecontroller", "dice"],
    "video game":           ["gamecontroller"],
    "controle":             ["gamecontroller"],
    "dado":                 ["dice"],
    "quebra cabeca":        ["puzzlepiece"],
    "musica":               ["music.note", "music.mic", "waveform"],
    "nota musical":         ["music.note"],
    "show":                 ["music.mic", "ticket"],
    "concerto":             ["music.mic", "ticket"],
    "cinema":               ["film", "ticket"],
    "filme":                ["film"],
    "bilhete":              ["ticket"],
    "ingresso":             ["ticket"],
    "teatro":               ["theatermasks"],
    "foto":                 ["photo", "camera"],
    "fotografia":           ["photo", "camera"],
    "camera":               ["camera", "photo"],
    "pintura":              ["paintbrush", "paintpalette"],
    "arte":                 ["paintbrush", "paintpalette"],
    "esporte":              ["sportscourt", "figure.run"],
    "quadra":               ["sportscourt"],
    "festa":                ["party.popper", "balloon", "confetti"],
    "fogos":                ["fireworks"],
    "viagem":               ["airplane", "suitcase"],
    "ferias":               ["beach.umbrella", "airplane", "suitcase"],

    // ── Moda & Estilo ─────────────────────────────────────────────────────
    "roupa":                ["tshirt"],
    "camisa":               ["tshirt"],
    "camiseta":             ["tshirt"],
    "bolsa":                ["handbag", "bag"],
    "sapato":               ["shoe"],
    "relogio":              ["watch.analog", "clock"],
    "coroa":                ["crown"],
    "brilho":               ["sparkles", "sparkle"],
    "etiqueta":             ["tag", "lanyardcard"],
    "presente":             ["gift"],
    "vale presente":        ["giftcard"],
    "loja":                 ["storefront", "building.storefront"],
    "moda":                 ["tshirt", "handbag"],
    "estilo":               ["sparkles", "crown"],

    // ── Dispositivos & Tecnologia ─────────────────────────────────────────
    "celular":              ["iphone"],
    "smartphone":           ["iphone"],
    "telefone celular":     ["iphone"],
    "tablet":               ["ipad"],
    "computador":           ["desktopcomputer", "macbook"],
    "notebook":             ["macbook"],
    "teclado":              ["keyboard"],
    "mouse":                ["computermouse"],
    "monitor":              ["display", "desktopcomputer"],
    "televisao":            ["tv"],
    "impressora":           ["printer"],
    "fone":                 ["headphones", "airpods", "earpods"],
    "fone de ouvido":       ["headphones", "airpods"],
    "bateria":              ["battery"],
    "carregador":           ["bolt.fill.batteryblock", "cable.connector"],
    "cabo":                 ["cable.connector"],
    "processador":          ["cpu"],
    "chip":                 ["cpu", "memorychip", "simcard"],
    "cartao sd":            ["sdcard"],
    "servidor":             ["server.rack"],
    "disco":                ["internaldrive", "externaldrive"],
    "bluetooth":            ["bluetooth"],
    "internet":             ["network", "wifi", "globe"],
    "roteador":             ["wifi.router"],

    // ── Interface & Ações ─────────────────────────────────────────────────
    "configuracao":         ["gear", "gearshape"],
    "ajuste":               ["slider", "gear"],
    "busca":                ["magnifyingglass"],
    "filtro":               ["slider.horizontal"],
    "compartilhar":         ["square.and.arrow.up"],
    "baixar":               ["square.and.arrow.down", "arrow.down.circle"],
    "download":             ["square.and.arrow.down", "arrow.down"],
    "subir":                ["square.and.arrow.up", "arrow.up.circle"],
    "upload":               ["square.and.arrow.up", "arrow.up"],
    "apagar":               ["trash", "xmark"],
    "deletar":              ["trash"],
    "editar":               ["pencil", "square.and.pencil"],
    "copiar":               ["doc.on.doc", "doc.on.clipboard"],
    "colar":                ["doc.on.clipboard"],
    "desfazer":             ["arrow.uturn.backward"],
    "refazer":              ["arrow.uturn.forward"],
    "fechar":               ["xmark.circle"],
    "cancelar":             ["xmark", "xmark.circle"],
    "confirmar":            ["checkmark", "checkmark.circle"],
    "salvar":               ["square.and.arrow.down", "icloud.and.arrow.up"],
    "favorito":             ["star", "heart", "bookmark"],
    "marcador":             ["bookmark"],
    "adicionar":            ["plus", "plus.circle"],
    "mais":                 ["plus"],
    "menos":                ["minus"],
    "voltar":               ["arrow.left", "chevron.left"],
    "avancar":              ["arrow.right", "chevron.right"],
    "atualizar":            ["arrow.clockwise"],
    "sincronizar":          ["arrow.triangle.2.circlepath"],
    "menu":                 ["list.bullet", "ellipsis"],
    "opcoes":               ["ellipsis", "slider.horizontal"],
    "info":                 ["info.circle"],
    "ajuda":                ["questionmark.circle"],
    "aviso":                ["exclamationmark.circle", "exclamationmark.triangle"],
    "erro":                 ["xmark.circle", "exclamationmark.octagon"],
    "sucesso":              ["checkmark.circle"],
    "privacidade":          ["lock", "shield", "eye.slash"],
    "seguranca":            ["lock", "shield", "key"],
    "senha":                ["lock", "key"],
    "biometria":            ["touchid", "faceid"],
    "visivel":              ["eye"],
    "invisivel":            ["eye.slash"],
    "grade":                ["square.grid.2x2", "square.grid.3x3"],
    "layout":               ["rectangle.grid.2x2", "sidebar.left"],
    "tema":                 ["paintpalette", "circle.lefthalf.filled"],
    "escuro":               ["moon.fill", "circle.righthalf.filled"],
    "claro":                ["sun.max.fill", "circle.lefthalf.filled"],
    "link":                 ["link"],
    "qr code":              ["qrcode"],
    "codigo de barras":     ["barcode"],
    "localizacao":          ["location", "mappin"],
    "mapa":                 ["map"],

    // ── Tempo ─────────────────────────────────────────────────────────────
    "hora":                 ["clock"],
    "tempo":                ["clock", "timer"],
    "cronometro":           ["stopwatch"],
    "temporizador":         ["timer"],
    "alarme":               ["alarm"],
    "agenda":               ["calendar"],
    "calendario":           ["calendar"],
    "data":                 ["calendar"],
    "prazo":                ["calendar.badge.clock"],
    "vencimento":           ["calendar.badge.clock"],
    "historico":            ["clock.arrow.circlepath"],
    "recorrente":           ["repeat"],
    "parcelado":            ["repeat", "square.stack"],

    // ── Geral ─────────────────────────────────────────────────────────────
    "cubo":                 ["cube"],
    "caixa":                ["archivebox", "shippingbox"],
    "encomenda":            ["shippingbox"],
    "mala":                 ["suitcase", "latch.2.case"],
    "bolsa medica":         ["cross.case"],
    "maleta":               ["briefcase"],
    "cracha":               ["lanyardcard"],
    "medalha":              ["crown", "seal"],
    "trofeu":               ["trophy"],
    "classificacao":        ["star", "chart.bar"],
    "avaliacao":            ["star"],
    "curtir":               ["heart", "hand.thumbsup"],
    "descurtir":            ["hand.thumbsdown"],
    "bandeira":             ["flag"],
    "pino":                 ["mappin"],
    "placa":                ["signpost.left", "signpost.right"],
    "engrenagem":           ["gear", "gearshape"],
    "ferramenta":           ["wrench", "hammer", "screwdriver"],
    "martelo":              ["hammer"],
    "chave de fenda":       ["screwdriver"],
    "chave inglesa":        ["wrench"],
    "pincel":               ["paintbrush"],
    "tesoura":              ["scissors"],
    "lixo":                 ["trash"],
    "lixeira":              ["trash"],
    "recorte":              ["scissors"],
    "impressao":            ["printer"],
    "infinito":             ["infinity"],
    "nota":                 ["note", "banknote"],
    "wifi":                 ["wifi"],
    "tenis":                ["shoe", "figure.tennis"],
    "porcentual":           ["percent"],
    "video":                ["video", "film"],
]
// swiftlint:enable file_length
